config/routes.rb
Rails.application.routes.draw do
  devise_for :resource_owners
  devise_for :posts
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :bug_reports
  get 'faq/index'
  get 'welcome/index'
  get 'resources/unapproved', to: 'resources#unapproved'
  get 'resources/archived', to: 'resources#archived'
  get 'resources/flagged', to: 'resources#flagged'
  get 'resources/all', to: 'resources#all'
  # get 'resources/:email/edit', to: 'resources#owner_edit', as: "owner_edit_resource",  constraints: { email: /.+@.+\..*/ }
  post 'resources/:id/confirm', to: 'resources#confirm', as: "confirm"
  # If a 'display user information' page gets added, may be good idea to move location
  # of flash key button to that page.
  devise_scope :user do
    get 'user/showkey', to: 'users/registrations#showkey', as: 'showkey_user'
  end
  resources :resources, :defaults => {:format => 'json'}

  match 'resources/approve/many' => 'resources#approve_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/archive/many' => 'resources#archive_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/delete/many' => 'resources#delete_many', via: [:delete], :defaults => {:format => 'json'}

  match 'resources/approve/:id' => 'resources#update', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/archive/:id' => 'resources#archive', as: :resources_archive, via: [:put, :post, :patch]
  match 'resources/restore/:id' => 'resources#restore', as: :resources_restore, via: [:put, :post, :patch]
  match 'resources/flag/:id' => 'resources#flag', as: :resources_flag, via: [:put, :post, :patch]

  match 'resources/unapproved' => 'resources#upload', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  root "welcome#index"
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/all.html.erb
<div class="top" id="approval-title">
  <h1>Resources</h1>
<!--</div>-->
<%# if flash[:notice] %>
<!--  <p class="notice"><%#= flash[:notice] %></p>-->
<%# end %>
<div id="all"  id="resource-container-wrapper">
    <div id="approval-column">
        <% @resources.each do |resource| %>
        <div class="row resource-container unapproved-resource">
            
            <div class="links" %>
            <%= link_to("View Resource", "/resources/" + resource.id.to_s + ".html", class: "btn btn-outline-primary") %>
            
            <%= link_to('Edit', edit_resource_path(resource), class: "btn btn-outline-primary") %>
            <% if user_signed_in? %>
                <%= link_to 'Archive', resources_archive_path(resource), method: :put, data: { confirm: "Are you sure you want to archive?", id: resource["id"] } , class: "btn btn-outline-primary btn-archive", id: resource["id"] %>
            <% elsif resource_owner_signed_in?%>
                <%= link_to('Confirm', confirm_path(resource["id"]), method: :post, class: "btn btn-outline-primary") %>
              <% end %>

            </div>
            <div class="resource-title text">
                <%= resource.title %>
            </div>

            <div class="approval-checkbox">
            <%= check_box_tag 'approve_list[]', resource.id, checked=false %>
            </div>

            <div>
            <% i = 0 %>
            <% @all_values_hash.map do |key, value| %>
                <% text = resource[value]%>
                <% if (@has_many_hash.key?(value)) %>
                    <% text = resource.send(value).collect(&:val) %>
                    <% text = text.to_s.gsub(/[^0-9A-Za-z,\s,\-,\&]/, "") %>
                <% end %>
                <% if (text != nil && text.to_s.length != 0) %>
                    <% if (i % 2 == 1) %>
                        <div class="text colored">
                    <% else %>
                        <div class="text">
                    <% end %>
                        <p><b><%= key.to_s + ": "%></b> <%= text.to_s %></p>
                    </div>
                    <% i += 1 %>
                <% end %>
                
            <% end %>
        </div>
        </div>
    <% end %>
    </div>
    
</div>
</div>
</div>

app/views/resources/archived.html.erb
<div class="top" id="approval-title">
  <h1>Archived Resources</h1>
</div>

<div id="archived"  id="resource-container-wrapper">
    <div class="col" id="approval-column">

      <div class="links">
        <%= form_tag("/resources/delete/many.html", method: :delete) do %>
          <button class='btn btn-outline-dark btn-all' id="delete-all-button" name="approve_list" value="all" data-confirm="Are you sure you want to delete all resources? This cannot be undone.">
            Delete All
          </button>
        <% end %>
        <a class="nav-item btn btn-outline-dark" href="/resources/unapproved.html">View approval queue</a>
      </div>

      <div id="result-header">
        <h2><%= @resource_count %> archived</h2>
      </div>
      
      
      <% @resources.each do |resource| %>
        <div class="row resource-container unapproved-resource">
            
            <div class="links" %>
              <%= link_to("View Resource", "/resources/" + resource.id.to_s + ".html", class: "btn btn-outline-primary") %>

              <%= link_to('Edit', edit_resource_path(resource), class: "btn btn-outline-primary") %>

              <%= button_to 'Restore', resources_restore_path(resource), data: { confirm: "Are you sure you want to restore?", id: resource["id"] } , class: "btn btn-outline-primary btn-restore", id: resource["id"] %>
              
              <%= button_to 'Delete', resource, method: :delete, data: { confirm: "Are you sure you want to delete this resource? This cannot be undone." }, class: "btn btn-outline-primary", id: "btn-delete" %>
            </div>
            <div class="resource-title text">
                <%= resource.title %>
            </div>
            <div class="approval-checkbox">
              <%= check_box_tag 'approve_list[]', resource.id, checked=false %>
            </div>
            <% all_values = @all_values_hash %>
            <div>
              <% i = 0 %>
              <% @all_values_hash.map do |key, value| %>
                  <% text = resource[value]%>
                  <% if (@has_many_hash.key?(value)) %>
                      <% text = resource.send(value).collect(&:val) %>
                      <% text = text.to_s.gsub(/[^0-9A-Za-z,\s,\-,\&]/, "") %>
                  <% end %>
                  <% if (text != nil && text.to_s.length != 0) %>
                      <% if (i % 2 == 1) %>
                          <div class="text colored">
                      <% else %>
                          <div class="text">
                      <% end %>
                          <p><b><%= key.to_s + ": "%></b> <%= text.to_s %></p>
                      </div>
                      <% i += 1 %>
                  <% end %>
              <% end %>
          </div>
        </div>
      <% end %>
  </div>
  
</div>

app/views/resources/edit.html.erb
<div id="new" class="edit">
<%= javascript_include_tag "new" %>
<%= javascript_include_tag "filter" %>

<div id="suggest_form">
    <div id="edit-top">
        <div id="edit-title" %>
            <h1>Editing:</h1>
            <h2><%= @resource.title%></h2>
        </div>
        <div class="links" %>
            <%= link_to("View Resource", "/resources/" + @resource.id.to_s + ".html", class: "btn btn-outline-primary") %>
        </div>
    </div>

  <%= form_tag("/resources/" + @resource.id.to_s + ".html", method: "patch", id: "form_section") do %>
    <div id="form_submit">
      <a> <button>Update</button></a>
      <%#= button_tag("Update", :id => "submit_button") %>
      <p id="message"><p>
    </div>
      <div class="form_step">
          <h2>Basic Information</h2>
          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:title, "Resource Name", class: "required") %>
                  <p> Title of the resource </p>
                  <%= text_field_tag(:title, @resource.title, class: "required_input") %>
              </div>
          </div>
        <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:url, "Resource URL", class: "required") %>
                  <p> Webpage for resource </p>
                  <%= text_field_tag(:url, @resource.url, class: "required_input") %>
              </div>
          </div>

          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:description, "Resource Description", class: "required") %>
                  <%= text_area_tag(:description, @resource.description, class: "required_input") %>
              </div>
          </div>

          <div class="resource_row association_row">
              <% @locations.each do |association, values| %>
                  <div id="location">
                      <%= label_tag(:location, association.capitalize, class: "required")%>
                  </div>
                  <div class="resource_checkboxes">
                      <% values.each do |val| %>
                            <div class="single_checkbox">
                                <% if @resource.location == val%>
                                    <div class="label loc-radio">
                                    <%= val %>
                                        <%= radio_button_tag association, val, true, class: "radio", id: val %>
                                    </div>
                                <% else %>
                                    <div class="label loc-radio">
                                        <%= val %>
                                        <%= radio_button_tag association, val, false, class: "radio", id: val %>
                                    </div>
                                <% end %>
                            </div>
                      <% end %>
                  </div>
              <% end %>
          </div>

          <% @has_many_hash.each do |association, values| %>
              <% if (association ==  "types" || association == "audiences")%>
                  <div class="association_row">
                      <div class="association">
                          <%= label_tag(:association, association.capitalize) %>
                      </div>
                      <div class="resource_checkboxes">
                          <% values.each do |val| %>
                                <div class="single_checkbox type_checkbox">
                                <% if @resource.send(association).collect(&:val).include?(val)%>
                                    <div class="label"><%= val %></div>
                                        <%= check_box_tag association+'[]', val, true, class: "checkbox", id: val %>
                                    </div>
                                <% else %>
                                    <div class="label"><%= val %></div>
                                        <%= check_box_tag association+'[]', val, false, class: "checkbox", id: val %>
                                    </div>
                                <% end %>
                          <% end %>
                      </div>
                  </div>
              <% end %>
          <% end %>
      </div>

      
      <div class="form_step">
          <h2>Additional Information</h2>

          <div class="contact_row">
                <div class="input_field col">
                    <%= label_tag(:resource_email, "Email - General") %>
                    <p class="label-desc-other">Email associated with this resource. </p>
                    <%= text_field_tag(:resource_email, @resource.resource_email) %>
                </div>
            </div>

            <div class="contact_row">
                <div class="input_field col">
                    <%= label_tag(:resource_phone, "Phone - General") %>
                    <p class="label-desc-other">Phone associated with this resource. </p>
                    <%= text_field_tag(:resource_phone, @resource.resource_phone) %>
                </div>
            </div>
            <div class="contact_row">
                <div class="input_field col">
                    <%= label_tag(:address, "Address") %>
                    <p class="label-desc-other">An organization's headquarters or an event's physical location. </p>
                    <%= text_field_tag(:address, @resource.address) %>
                </div>
            </div>

            <div class="resource_row">
                <div class="input_field other-info">
                    <%= label_tag(:deadline, "Deadline") %>
                    <p>The specific date applications are due, when an event is held, or when a resource becomes unavailable. The first or upcoming deadline.</p>
                    <% if @resource.deadline != nil %>
                        <%= date_field_tag(:deadline, @resource.deadline.to_date()) %>
                    <% else %>
                        <%= date_field_tag(:deadline, nil) %>
                    <% end %>
                </div>
            </div>

          <div class="association_row">
              <% @has_many_hash.each do |association, values| %>
                  <% if (association !=  "types" && association != "audiences")%>
                      <div class="association">
                          <%= label_tag(:association, association.capitalize.gsub(/[^0-9A-Za-z,\s]/, " ")) %>
                      </div>
                      <div class="resource_checkboxes">
                      <% values.each do |val| %>
                        <div class="single_checkbox type_checkbox">
                        <% if @resource.send(association).collect(&:val).include?(val)%>
                            <div class="label"><%= val %></div>
                                <%= check_box_tag association+'[]', val, true, class: "checkbox", id: val %>
                            </div>
                        <% else %>
                            <div class="label"><%= val %></div>
                                <%= check_box_tag association+'[]', val, false, class: "checkbox", id: val %>
                            </div>
                        <% end %>
                  <% end %>
                      </div>
                  <% end %>
              <% end %>
          </div>

          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:notes, "Notes") %>
                  <p> Note any other details on eligibility, deadlines, and process. </p>
                  <%= text_area_tag(:notes, @resource.notes) %>
              </div>
          </div>

          
      </div>

      <div class="form_step" id="contact_info">
          <h2>Contact Info for Resource Maintenance </h2>
            <div class="contact_row">
              <div class="input_field col">
                  <%= label_tag(:contact_email, "Contact Email", class: "required") %>
                  <p>Email of the person or organization we can contact to update the resource in our database if needed. </p>
                  <%= text_field_tag(:contact_email, @resource.contact_email, class: "required_input validate-input") %>
                    <p id="email-valid" class="invalid-text"> Invalid Email </p>
              </div>
            </div>
            <div class="contact_row">
              <div class="input_field col">
                  <%= label_tag(:contact_name, "Contact Name") %>
                  <p> The person who is most up-to-date with this resource's information</p>
                  <%= text_field_tag(:contact_name, @resource.contact_name) %>
              </div>
            </div>
            <div class="contact_row">
              <div class="input_field col">
                  <%= label_tag(:contact_phone, "Contact Phone") %>
                  <p> Who can we call if we have a question about the resource? </p>
                  <%= text_field_tag(:contact_phone, @resource.contact_phone, class: "validate-input") %>
                    <p id="phone-valid" class="invalid-text"> Invalid Phone </p>
              </div>
            </div>
      </div>

      <% if user_signed_in? %>
      <div class="form_step">
          <h2>Admin Information</h2>
          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:approval_status, "Approval Status") %>
                  <p> 0 = unapproved, 1 = approved, 2 = archived </p>
                  <%= text_field_tag(:approval_status, @resource.approval_status) %>
              </div>
            </div>
            <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:approval_status, "Flagged") %>
                  <p> 0 = no flag, 1 = flagged </p>
                  <%= text_field_tag(:flagged, @resource.flagged) %>
              </div>
          </div>

          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:flagged_comment, "Flagged comment") %>
                  <p> Any issues or outdated information about this resource. </p>
                  <%= text_area_tag(:flagged_comment, @resource.flagged_comment) %>
              </div>
          </div>

          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:approved_by, "Approved By") %>
                  <p>The person who approved the resource from the approval queue. </p>
                  <%= text_field_tag(:approved_by, @resource.approved_by) %>
              </div>
          </div>
        </div>
      <% end %>

      <div id="form_submit">
            <%= button_tag("Update", :id => "submit_button") %>
            <p id="message"><p>
        </div>

  <% end %>
</div>
</div>

app/views/resources/flagged.html.erb
<div class="top" id="approval-title">
  <h1>Flagged Resources</h1>
</div>

<div id="flagged"  id="resource-container-wrapper">
    <div class="col" id="approval-column">
        <div id="result-header">
          <h2><%= @resource_count %> awaiting corrections</h2>
        </div>
        
        
        <% @resources.each do |resource| %>
          <div class="row resource-container flagged">
              
              <div class="links" %>
                <%= link_to("View Resource", "/resources/" + resource.id.to_s + ".html", class: "btn btn-outline-primary") %>
                
                <%= link_to('Edit', edit_resource_path(resource), class: "btn btn-outline-primary") %>

                <%= link_to 'Remove Flag', resources_restore_path(resource), method: :put, data: { confirm: "Are you sure you want to remove the flag?", id: resource["id"] } , class: "btn btn-outline-primary", id: resource["id"] %>

                <%= link_to 'Archive', resources_archive_path(resource), method: :put, data: { confirm: "Are you sure you want to archive?", id: resource["id"] } , class: "btn btn-outline-primary btn-archive", id: resource["id"] %>
          
              </div>
              <div class="resource-title text">
                  <%= resource.title %>
              </div>

              <div class="approval-checkbox">
                <%= check_box_tag 'approve_list[]', resource.id, checked=false %>
              </div>

              <div>
                <% i = 0 %>
                <% @all_values_hash.map do |key, value| %>
                    <% text = resource[value]%>
                    <% if (@has_many_hash.key?(value)) %>
                        <% text = resource.send(value).collect(&:val) %>
                        <% text = text.to_s.gsub(/[^0-9A-Za-z,\s,\-,\&]/, "") %>
                    <% end %>
                    <% if (text != nil && text.to_s.length != 0) %>
                        <% if (i % 2 == 1) %>
                            <div class="text colored">
                        <% else %>
                            <div class="text">
                        <% end %>
                            <p><b><%= key.to_s + ": "%></b> <%= text.to_s %></p>
                        </div>
                        <% i += 1 %>
                    <% end %>
                    
                <% end %>
            </div>
          </div>
        <% end %>
      
  </div>
  
</div>

app/views/resources/index.html.erb
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />

<div class="top" id="resources-index">
    <h1>Resources </h1>
    <div class="submit-resource-container">
      <a class="submit-resource-button" href="/resources/new.html">Suggest a Resource</a>
     </div>
</div>


<%= javascript_pack_tag 'application' %>
<%= javascript_include_tag "filter" %>
<%= javascript_include_tag "resource-index" %>

<div class="index"  id="resource-container-wrapper">
  <% resource_data = @resources_json %>
  <% if user_signed_in? %>
    <%= react_component("Display", { filters: @has_many_hash.merge(@locations), child_locations: @child_locations, resources: resource_data, user_signed_in: true }) %>
  <% else %>
    <%= react_component("Display", { filters: @has_many_hash.merge(@locations), child_locations: @child_locations, resources: resource_data, user_signed_in: false }) %>
  <% end %>
</div>

app/views/resources/show.html.erb
<div id="show">

<%= javascript_include_tag "show" %>

<% if @resource == nil %>
    <div id="show-title">
        <h2>This page does not exist!</h2>
        <p>It might have previously existed, but is no longer available.</p>
    </div>
<% else %>
    <div id="resource_info">
        <div id="show-title">
            <h2><%= @resource["title"] %></h2>
        </div>
        <% if @resource["url"].to_s.length > 0 %>
            <div class="resource-detail detail-border-bot">
                <h3>Website</h3>
                <a href="<%= @resource["url"] %>"><%= @resource["url"][0...100] %></a>
            </div>
        <% end %>
        <% if @resource["description"].to_s.length > 0 %>
            <div class="resource-detail">
                <h3>Description</h3>
                <p><%= @resource["description"] %></p>
            </div>
        <% end %>
        <% if @resource["address"].to_s.length > 0 || @resource["location"].to_s.length > 0 %>
            <div class="resource-detail">
                <h3>Location</h3>
                <p><%= @resource["address"] %></p>
                <p><%= @resource["location"] %></p>
            </div>
        <% end %>
        <% if @resource["resource_email"].to_s.length > 0 %>
            <div class="resource-detail">
                <h3>Contact Information</h3>
                <p><%= @resource["resource_email"] %></p>
            </div>
        <% end %>
        <div class="resource-detail detail-border-top">
            <h3>Categories & Tags</h3>
            <% @has_many_hash.map do |key, value| %>
                <% if @resource[key].length > 0 %>
                    <div class="resource-tag">
                        <p><b><%= key.to_s.gsub(/[\_]/, " ").gsub(/[^0-9A-Za-z,\s,\-,\&]/, "").capitalize%></b><p>
                        <div class="show-tag">
                            <% @tags = @resource[key].to_s.split(',')%>
                            <% @tags.each do |tag| %>

                              <%if tag.to_s.include? "BrokenURL" %>
                                <% if user_signed_in? %>
                                  <div class="label">
                                  <%=  tag.gsub(/[^0-9A-Za-z,\s,\-,\&]/, "") %>
                                  </div>
                                <% end %>
                              <% else %>
                                <div class="label">
                                    <%=  tag.gsub(/[^0-9A-Za-z,\s,\-,\&]/, "") %>
                                </div>
                               <% end %>
                            <% end%>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <p class="resource-updated">Last Updated:  <%= @updated_at %> </p>
    </div>

    <div class="flag-section">
        <%= form_tag("/resources/flag/" + @resource["id"].to_s, method: "post", id: "form_section", class: "flag-form") do %>
            <div class="input_field">
                    <p> Please let us know what info is incorrect or outdated. </p>
                    <%= text_area_tag(:flagged_comment) %>
            </div>
                <%= button_to 'Submit', resources_flag_path(@resource), data: { id: @resource["id"] } , class: "btn btn-outline-primary", id: @resource["id"] %>
        <% end %>
        <button class="btn btn-outline-primary" id="flag-btn">Found something incorrect?</button>
    </div>

    <div class="links" %>
        <% if resource_owner_signed_in? and @resource["contact_email"] == current_resource_owner.email%>
        <%= link_to('Edit', edit_resource_path(@resource), class: "btn btn-outline-primary") %>
        <% elsif user_signed_in? %>
            <% all_values = @has_many_hash %>
            <%= link_to('Edit', edit_resource_path(@resource), class: "btn btn-outline-primary") %>
            
            <% if @resource["approval_status"] == 0 %>
                <a class="nav-item btn btn-outline-primary" href="/resources/unapproved.html">View in approval queue</a>
            <% end %> 

            <% if @resource["approval_status"] != 2 %>
                <%= button_to 'Archive', resources_archive_path(@resource), data: { confirm: "Are you sure you want to move this resource to the archive?", id: @resource["id"] } , class: "btn btn-outline-primary btn-archive", id: @resource["id"] %>
            <% else %>
                <a class="nav-item btn btn-outline-primary" href="/resources/archived.html">View in archive</a>
            <% end %>
        <% else %>
            <% all_values = @has_many_hash %>
        <% end %> 
        
    </div>
<% end %>

</div>

app/views/resources/unapproved.html.erb
<div class="top" id="approval-title">
  <h1>Approval Queue</h1>
</div>

<%= javascript_include_tag "unapproved" %>

<div id="unapproved"  id="resource-container-wrapper">
    <div class="col" id="approval-column">
      <%= form_for @upload do |f| %>
        <%= f.file_field :csv, class: "csv-button" %>
        <%= f.submit 'Upload resources from CSV file', class: 'btn btn-outline-dark csv-button' %>
      <% end %>

      <div class="links">
        <%= form_tag("/resources/approve/many.html", method: :post) do %>
          <button class='btn btn-outline-dark' id="approve-all-button" name="approve_list" value="all" data-confirm="Are you sure you want to approve all resources in the queue?">
            Approve All
          </button>
        <% end %>

        <%= form_tag("/resources/archive/many.html", method: :post) do %>
          <button class='btn btn-outline-dark' id="archive-all-button" name="approve_list" value="all" data-confirm="Are you sure you want to archive all resources in the queue?">
            Archive All
          </button>
        <% end %>

        <a class="nav-item btn btn-outline-dark" href="/resources/archived.html">View archived resources</a>
      </div>

      

      <%= form_tag("/resources/approve/many.html", method: :post) do %>
        <div id="result-header">
          <h2><%= @resource_count %> awaiting approval</h2>
          <%= submit_tag 'Approve selected resources', class: 'btn btn-outline-dark approve-button' %>
        </div>
        
        
        <% @resources.each do |resource| %>
          <div class="row resource-container unapproved-resource">
              
              <div class="links" %>
                <%= link_to("View Resource", "/resources/" + resource.id.to_s + ".html", class: "btn btn-outline-primary") %>
                
                <%= link_to('Edit', edit_resource_path(resource), class: "btn btn-outline-primary") %>

                <%= link_to 'Archive', resources_archive_path(resource), method: :put, data: { confirm: "Are you sure you want to archive?", id: resource["id"] } , class: "btn btn-outline-primary btn-archive", id: resource["id"] %>
          
              </div>
              <div class="resource-title text">
                  <%= resource.title %>
              </div>

              <div class="approval-checkbox">
                <%= check_box_tag 'approve_list[]', resource.id, checked=false %>
              </div>

              <div>
                <% i = 0 %>
                <% @all_values_hash.map do |key, value| %>
                    <% text = resource[value]%>
                    <% if (@has_many_hash.key?(value)) %>
                        <% text = resource.send(value).collect(&:val) %>
                        <% text = text.to_s.gsub(/[^0-9A-Za-z,\s,\-,\&]/, "") %>
                    <% end %>
                    <% if (text != nil && text.to_s.length != 0) %>
                        <% if (i % 2 == 1) %>
                            <div class="text colored">
                        <% else %>
                            <div class="text">
                        <% end %>
                            <p><b><%= key.to_s + ": "%></b> <%= text.to_s %></p>
                        </div>
                        <% i += 1 %>
                    <% end %>
                    
                <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      
  </div>
  
</div>