config/routes.rb
Rails.application.routes.draw do
  devise_for :resource_owners
  devise_for :posts
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :bug_reports
  get 'faq/index'
  get 'welcome/index'
  get 'resources/unapproved', to: 'resources#unapproved'
  get 'resources/archived', to: 'resources#archived'
  get 'resources/flagged', to: 'resources#flagged'
  get 'resources/all', to: 'resources#all'
  # get 'resources/:email/edit', to: 'resources#owner_edit', as: "owner_edit_resource",  constraints: { email: /.+@.+\..*/ }
  post 'resources/:id/confirm', to: 'resources#confirm', as: "confirm"
  # If a 'display user information' page gets added, may be good idea to move location
  # of flash key button to that page.
  devise_scope :user do
    get 'user/showkey', to: 'users/registrations#showkey', as: 'showkey_user'
  end
  resources :resources, :defaults => {:format => 'json'}

  match 'resources/approve/many' => 'resources#approve_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/archive/many' => 'resources#archive_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/delete/many' => 'resources#delete_many', via: [:delete], :defaults => {:format => 'json'}

  match 'resources/approve/:id' => 'resources#update', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/archive/:id' => 'resources#archive', as: :resources_archive, via: [:put, :post, :patch]
  match 'resources/restore/:id' => 'resources#restore', as: :resources_restore, via: [:put, :post, :patch]
  match 'resources/flag/:id' => 'resources#flag', as: :resources_flag, via: [:put, :post, :patch]

  match 'resources/unapproved' => 'resources#upload', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  root "welcome#index"
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bug_report.rb
class BugReport < ApplicationRecord

end

app/controllers/bug_reports_controller.rb
class BugReportsController < ApplicationController
  before_action :set_bug_report, only: [:show, :edit, :update, :destroy]
  before_action :access_control, only: [:index, :show, :edit, :update, :destroy]

  # GET /bug_reports
  # GET /bug_reports.json
  def index
    @bug_reports = BugReport.all
  end

  # GET /bug_reports/1
  # GET /bug_reports/1.json
  def show
    @bug_report = BugReport.find(params[:id])
  end

  # GET /bug_reports/new
  def new
    @bug_report = BugReport.new
  end

  # GET /bug_reports/1/edit
  def edit

  end

  # POST /bug_reports
  # POST /bug_reports.json
  def create
    @bug_report = BugReport.new(bug_report_params)
    @bug_report.closed = false;

    respond_to do |format|
      if @bug_report.save
        format.html { redirect_to "/", notice: 'Successfully submitted feedback!' }
        format.json { render :show, status: :created, location: @bug_report }
      else
        format.html { render :new }
        format.json { render json: @bug_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bug_reports/1
  # PATCH/PUT /bug_reports/1.json
  def update
    respond_to do |format|
      if @bug_report.update(bug_report_params)
        format.html { redirect_to @bug_report, notice: 'Successfully updated feedback!' }
        format.json { render :show, status: :ok, location: @bug_report }
      else
        format.html { render :edit }
        format.json { render json: @bug_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bug_reports/1
  # DELETE /bug_reports/1.json
  def destroy
    @bug_report.destroy()
    respond_to do |format|
      format.html { redirect_to bug_reports_url, notice: 'Successfully deleted feedback!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug_report
      if BugReport.exists?(params[:id])
        @bug_report = BugReport.find(params[:id])
      else
        redirect_to bug_reports_url
      end
    end

    def access_control
      if !user_signed_in?
        flash[:alert] = "You must be logged in to access this page"
        redirect_to welcome_index_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_report_params
      params.require(:bug_report).permit(:desc, :name, :email, :closed)
    end
end

app/helpers/bug_reports_helper.rb
module BugReportsHelper
end

app/helpers/bugreports_helper.rb
module BugreportsHelper
end

app/views/bug_reports/_form.html.erb
<%= form_with(model: bug_report, local: true) do |form| %>
  <% if bug_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug_report.errors.count, "error") %> prohibited this bug_report from being saved:</h2>

      <ul>
      <% bug_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  

  <div class="field">
    <%= form.label :desc, "Description" %>
    <%= form.text_area :desc %>
  </div>

  <div class="field">
    <%= form.label :name, "Name (optional)" %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :email, "Email (optional)" %>
    <%= form.text_area :email %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bug_reports/edit.html.erb
<div id="bug-wrapper">
<h1>Editing Bug Report</h1>

<%= form_with(model: @bug_report, local: true) do |form| %>
    <% if @bug_report.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@bug_report.errors.count, "error") %> prohibited this bug_report from being saved:</h2>
  
        <ul>
        <% @bug_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :desc, "Description" %>
      <%= form.text_area :desc %>
    </div>

    <div class="bug-checkbox">
        <%= form.label :closed %>
        <%= form.check_box :closed %>
    </div>
  
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>



<div class="bug-navigation">
    <%= link_to 'View', @bug_report %> |
    <%= link_to 'Delete', { action: :destroy, id: @bug_report.id }, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
</div>

app/views/bug_reports/index.html.erb
<div id="bug-wrapper">

<h1 id="bug-title">Feedback Reports</h1>

<div class= "container" id="bug-report-container">
  <% @bug_reports.each do |bug_report| %>
    <% unless bug_report.closed %>
      <div class="bug-report-description">
        <p class="bug-report-desc-text"> <strong>Name:</strong> <%= bug_report.name %> </p>
        <p class="bug-report-desc-text"> <strong>Email:</strong> <%= bug_report.email %> </p>
        <p class="bug-report-desc-text"> <strong>Description:</strong> <%= bug_report.desc %> </p>
        <p class="bug-report-desc-text"> <strong>Closed:</strong> <%= bug_report.closed %> </p>
        <%= link_to("View", "/bug_reports/" + bug_report.id.to_s + ".html", class: "bug-btn") %>
      </div>
    <% end %>
  <% end %>
  <%= link_to 'New Feedback', new_bug_report_path, id: "new-bug" %>
</div>


</div>

app/views/bug_reports/new.html.erb
<div id="bug-wrapper">

<h1>Feedback</h1>

<h2 id="bug-desc">You can contact us through this form to report bugs or submit feedback! Please be as detailed as possible.</h2>

<%= render 'form', bug_report: @bug_report %>

</div>

app/views/bug_reports/show.html.erb
<div id="bug-wrapper-show">

<div class="bug-report-description">
  <p class="bug-report-desc-text">
    <strong>Name:</strong>
    <%= @bug_report.name %>
  </p>
  <p class="bug-report-desc-text">
    <strong>Email:</strong>
    <%= @bug_report.email %>
  </p>
  <p class="bug-report-desc-text">
    <strong>Description:</strong>
    <%= @bug_report.desc %>
  </p>


  <p class="bug-report-desc-text">
    <strong>Closed:</strong>
    <%= @bug_report.closed %>
  </p>
</div>


<div class="bug-navigation">
  <%= link_to 'Edit', edit_bug_report_path(@bug_report) %> |
  <%= link_to 'Back', bug_reports_path %>
</div>

</div>