config/routes.rb
Rails.application.routes.draw do
  devise_for :resource_owners
  devise_for :posts
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :bug_reports
  get 'faq/index'
  get 'welcome/index'
  get 'resources/unapproved', to: 'resources#unapproved'
  get 'resources/archived', to: 'resources#archived'
  get 'resources/flagged', to: 'resources#flagged'
  get 'resources/all', to: 'resources#all'
  # get 'resources/:email/edit', to: 'resources#owner_edit', as: "owner_edit_resource",  constraints: { email: /.+@.+\..*/ }
  post 'resources/:id/confirm', to: 'resources#confirm', as: "confirm"
  # If a 'display user information' page gets added, may be good idea to move location
  # of flash key button to that page.
  devise_scope :user do
    get 'user/showkey', to: 'users/registrations#showkey', as: 'showkey_user'
  end
  resources :resources, :defaults => {:format => 'json'}

  match 'resources/approve/many' => 'resources#approve_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/archive/many' => 'resources#archive_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/delete/many' => 'resources#delete_many', via: [:delete], :defaults => {:format => 'json'}

  match 'resources/approve/:id' => 'resources#update', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/archive/:id' => 'resources#archive', as: :resources_archive, via: [:put, :post, :patch]
  match 'resources/restore/:id' => 'resources#restore', as: :resources_restore, via: [:put, :post, :patch]
  match 'resources/flag/:id' => 'resources#flag', as: :resources_flag, via: [:put, :post, :patch]

  match 'resources/unapproved' => 'resources#upload', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  root "welcome#index"
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Innovation Resource Database</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': false %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
  </head>

  <body>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

    <nav class="navbar">
      <div id="left-nav">
        <% if user_signed_in? %>
          <a class="nav-link nav-item" href="/">Home</a>
          <a class="nav-link nav-item" href="/resources.html/">Resources</a>
          <div class="dropdown">
            <a class="dropbtn nav-link nav-item" href="/resources/all.html">Manage Resources</a>
            <div class="dropdown-content">
              <a class="nav-link nav-item" href="/resources/unapproved.html">Approval Queue</a>
              <a class="nav-link nav-item" href="/resources/flagged.html">Flagged Resources</a>
              <a class="nav-link nav-item" href="/resources/archived.html">Archived Resources</a>
            </div>
          </div>
        <% else %>
          <a class="nav-link nav-item" href="/">Home</a>
          <div class="dropdown">
            <a class="nav-link nav-item" href="/resources.html/">Resources</a>
          </div>
          <div class="dropdown">
            <a class="dropbtn nav-link nav-item" href="/faq/index.html">FAQ</a>
          </div>
      <% end %>
      </div>

      <div id="right-nav">
        <% if user_signed_in? %>
          <div class="dropdown">
            <%= link_to('Submit a Bug', new_bug_report_path, method: :get, class: 'admin-button nav-link') %>
            <div class="dropdown-content">
              <%= link_to('View Feedback', bug_reports_path, method: :get, class: 'admin-button nav-link nav-item') %>
            </div>
          </div>
          <div class="dropdown">
            <%= link_to('Edit Account', edit_user_registration_path, method: :get, class: 'admin-button nav-link') %>
            <div class="dropdown-content">
              <%= link_to('API Key', showkey_user_path, method: :get, class: 'admin-button nav-link') %>
            </div>
          </div>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'admin-button nav-link') %>
        <% elsif resource_owner_signed_in?%>
          <%= link_to('Submit a Bug', new_bug_report_path, method: :get, class: 'admin-button nav-link') %>
          <%= link_to('My Resources', resources_all_path, class: 'admin-button nav-link') %>
          <%= link_to('Logout', destroy_resource_owner_session_path, method: :delete, class: 'admin-button nav-link') %>
        <% else %>
          <%= link_to('Submit a Bug', new_bug_report_path, method: :get, class: 'admin-button nav-link') %>
          <%= link_to('Log in', new_resource_owner_session_path, class: 'admin-button nav-link') %>
          <%= link_to('Admin', new_user_session_path, class: 'admin-button nav-link')  %>

          <%#= link_to('Admin Registration', new_user_registration_path, class: 'admin-button nav-link') %>
        <% end %>
      </div>
      <% if false %>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
      <% end %>
    </nav>
    
    <%= yield %>
  </body>
  
</html>